//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activator.Presenter.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Advanced {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Advanced() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Activator.Presenter.Lang.Advanced", typeof(Advanced).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataUI Error.
        /// </summary>
        internal static string DataUI_Error {
            get {
                return ResourceManager.GetString("DataUI_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataUI Success.
        /// </summary>
        internal static string DataUI_Success {
            get {
                return ResourceManager.GetString("DataUI_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot Error.
        /// </summary>
        internal static string Reboot_Error {
            get {
                return ResourceManager.GetString("Reboot_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot Success.
        /// </summary>
        internal static string Reboot_Success {
            get {
                return ResourceManager.GetString("Reboot_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestoreDefaults Error.
        /// </summary>
        internal static string RestoreDefaults_Error {
            get {
                return ResourceManager.GetString("RestoreDefaults_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestoreDefaults Success.
        /// </summary>
        internal static string RestoreDefaults_Success {
            get {
                return ResourceManager.GetString("RestoreDefaults_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBaudRate Error.
        /// </summary>
        internal static string SetBaudRate_Error {
            get {
                return ResourceManager.GetString("SetBaudRate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBaudRate Success.
        /// </summary>
        internal static string SetBaudRate_Success {
            get {
                return ResourceManager.GetString("SetBaudRate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBitRate Error.
        /// </summary>
        internal static string SetBitRate_Error {
            get {
                return ResourceManager.GetString("SetBitRate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBitRate Success.
        /// </summary>
        internal static string SetBitRate_Success {
            get {
                return ResourceManager.GetString("SetBitRate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBusAddress Error.
        /// </summary>
        internal static string SetBusAddress_Error {
            get {
                return ResourceManager.GetString("SetBusAddress_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBusAddress Success.
        /// </summary>
        internal static string SetBusAddress_Success {
            get {
                return ResourceManager.GetString("SetBusAddress_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetFrequency Error.
        /// </summary>
        internal static string SetFrequency_Error {
            get {
                return ResourceManager.GetString("SetFrequency_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetFrequency Success.
        /// </summary>
        internal static string SetFrequency_Success {
            get {
                return ResourceManager.GetString("SetFrequency_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetInterval Error.
        /// </summary>
        internal static string SetInterval_Error {
            get {
                return ResourceManager.GetString("SetInterval_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetInterval Success.
        /// </summary>
        internal static string SetInterval_Success {
            get {
                return ResourceManager.GetString("SetInterval_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetName Error.
        /// </summary>
        internal static string SetName_Error {
            get {
                return ResourceManager.GetString("SetName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetName Success.
        /// </summary>
        internal static string SetName_Success {
            get {
                return ResourceManager.GetString("SetName_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetPower Error.
        /// </summary>
        internal static string SetPower_Error {
            get {
                return ResourceManager.GetString("SetPower_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetPower Success.
        /// </summary>
        internal static string SetPower_Success {
            get {
                return ResourceManager.GetString("SetPower_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetRssi Error.
        /// </summary>
        internal static string SetRssi_Error {
            get {
                return ResourceManager.GetString("SetRssi_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetRssi Success.
        /// </summary>
        internal static string SetRssi_Success {
            get {
                return ResourceManager.GetString("SetRssi_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetSerialNumber Error.
        /// </summary>
        internal static string SetSerialNumber_Error {
            get {
                return ResourceManager.GetString("SetSerialNumber_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetSerialNumber Success.
        /// </summary>
        internal static string SetSerialNumber_Success {
            get {
                return ResourceManager.GetString("SetSerialNumber_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetTriggerType Error.
        /// </summary>
        internal static string SetTriggerType_Error {
            get {
                return ResourceManager.GetString("SetTriggerType_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetTriggerType Success.
        /// </summary>
        internal static string SetTriggerType_Success {
            get {
                return ResourceManager.GetString("SetTriggerType_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVerifyCode Error.
        /// </summary>
        internal static string SetVerifyCode_Error {
            get {
                return ResourceManager.GetString("SetVerifyCode_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVerifyCode Success.
        /// </summary>
        internal static string SetVerifyCode_Success {
            get {
                return ResourceManager.GetString("SetVerifyCode_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetWorkType Error.
        /// </summary>
        internal static string SetWorkType_Error {
            get {
                return ResourceManager.GetString("SetWorkType_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetWorkType Success.
        /// </summary>
        internal static string SetWorkType_Success {
            get {
                return ResourceManager.GetString("SetWorkType_Success", resourceCulture);
            }
        }
    }
}
