//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activator.Presenter.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Activator.Presenter.Lang.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Error.
        /// </summary>
        internal static string Connect_Error {
            get {
                return ResourceManager.GetString("Connect_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Success.
        /// </summary>
        internal static string Connect_Success {
            get {
                return ResourceManager.GetString("Connect_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect Error.
        /// </summary>
        internal static string Disconnect_Error {
            get {
                return ResourceManager.GetString("Disconnect_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect Success.
        /// </summary>
        internal static string Disconnect_Success {
            get {
                return ResourceManager.GetString("Disconnect_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetInterval Error.
        /// </summary>
        internal static string SetInterval_Error {
            get {
                return ResourceManager.GetString("SetInterval_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetInterval Success.
        /// </summary>
        internal static string SetInterval_Success {
            get {
                return ResourceManager.GetString("SetInterval_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetPower Error.
        /// </summary>
        internal static string SetPower_Error {
            get {
                return ResourceManager.GetString("SetPower_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetPower Success.
        /// </summary>
        internal static string SetPower_Success {
            get {
                return ResourceManager.GetString("SetPower_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetRssi Error.
        /// </summary>
        internal static string SetRssi_Error {
            get {
                return ResourceManager.GetString("SetRssi_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetRssi Success.
        /// </summary>
        internal static string SetRssi_Success {
            get {
                return ResourceManager.GetString("SetRssi_Success", resourceCulture);
            }
        }
    }
}
