//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activator.View.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Advanced {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Advanced() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Activator.View.Lang.Advanced", typeof(Advanced).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud Rate (0 - 5) (default: 9600).
        /// </summary>
        internal static string BaudRateContainer {
            get {
                return ResourceManager.GetString("BaudRateContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit Rate (0 - 28) (default: 28).
        /// </summary>
        internal static string BitRateContainer {
            get {
                return ResourceManager.GetString("BitRateContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Address (0 - 255).
        /// </summary>
        internal static string BusAddressContainer {
            get {
                return ResourceManager.GetString("BusAddressContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataUI Error.
        /// </summary>
        internal static string DataUI_Error {
            get {
                return ResourceManager.GetString("DataUI_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataUI Success.
        /// </summary>
        internal static string DataUI_Success {
            get {
                return ResourceManager.GetString("DataUI_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string FormName {
            get {
                return ResourceManager.GetString("FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency (0 - 23) (default: 2480 MHz).
        /// </summary>
        internal static string FrequencyContainer {
            get {
                return ResourceManager.GetString("FrequencyContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval (0 - 65535) (default: 200).
        /// </summary>
        internal static string IntervalContainer {
            get {
                return ResourceManager.GetString("IntervalContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (8 chars).
        /// </summary>
        internal static string NameContainer {
            get {
                return ResourceManager.GetString("NameContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power (0 - 3) (default: 0).
        /// </summary>
        internal static string PowerContainer {
            get {
                return ResourceManager.GetString("PowerContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        internal static string RebootContainer {
            get {
                return ResourceManager.GetString("RebootContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore default parameters.
        /// </summary>
        internal static string RestoreDefaultsContainer {
            get {
                return ResourceManager.GetString("RestoreDefaultsContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSSI (0 - 31) (default: 0).
        /// </summary>
        internal static string RssiContainer {
            get {
                return ResourceManager.GetString("RssiContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number (8 chars).
        /// </summary>
        internal static string SerialNumberContainer {
            get {
                return ResourceManager.GetString("SerialNumberContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string TabControlPage1 {
            get {
                return ResourceManager.GetString("TabControlPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string TabControlPage2 {
            get {
                return ResourceManager.GetString("TabControlPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Type (0 - 7) (default: 1).
        /// </summary>
        internal static string TriggerTypeContainer {
            get {
                return ResourceManager.GetString("TriggerTypeContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Code (0 - 255) (default: 104).
        /// </summary>
        internal static string VerifyCodeContainer {
            get {
                return ResourceManager.GetString("VerifyCodeContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Type (0 - 7) (default: 0).
        /// </summary>
        internal static string WorkTypeContainer {
            get {
                return ResourceManager.GetString("WorkTypeContainer", resourceCulture);
            }
        }
    }
}
